prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}
    retention: 12h
    resources:
      requests:
        cpu: 150m
        memory: 750Mi
      limits:
        cpu: 500m
        memory: 2Gi
  service:
    type: NodePort
    nodePort: 30900

grafana:
  enabled: true
  service:
    type: NodePort
    nodePort: 30901
  adminPassword: admin
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards

alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 4h
      receiver: 'null'
    receivers:
    - name: 'null'
  service:
    type: NodePort
    nodePort: 30902 