namespace: project-monitoring

alerts:
  enabled: true

nginx:
  image: nginx:latest
  service:
    type: NodePort
    nodePort: 30903

kube-prometheus-stack:
  grafana:
    adminUser: admin
    adminPassword: admin
    service:
      type: NodePort
      nodePort: 30900
    persistence:
      enabled: true
      size: 1Gi
      storageClassName: local-path  # <- or your actual storage class
      accessModes:
        - ReadWriteOnce
    sidecar:
      dashboards:
        enabled: true

  prometheus:
    service:
      type: NodePort
      nodePort: 30901

