apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: complex-app-metrics
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: complex-app
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
