apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: resource-usage-alerts
  namespace: { { .Values.namespace | default "project-monitoring" } }
  labels:
    release: { { .Release.Name } }
spec:
  groups:
    - name: resource.rules
      rules:
        - alert: TestAlert
          expr: vector(1)
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Test alert fired on pod {{`{{ $labels.pod }}`}}"
            description: "This is a test description including pod {{`{{ $labels.pod }}`}} and namespace {{`{{ $labels.namespace }}`}}."
