apiVersion: v1
kind: ConfigMap
metadata:
  name: project-nginx-config
  namespace: { { .Values.namespace } }
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Raz-Config-Web</title>
      <style>
        body {
          background-color: #f0f0f0;
          font-family: Arial, sans-serif;
          text-align: center;
          padding-top: 50px;
        }

        h1 {
          color: #333;
        }

        p {
           color: red;
        }
      </style>
    </head>
    <body>
      <h1>Hello from This Is My Dev Page!</h1>
      <p>This page is served from a MountConfigMap.</p>
    </body>
    </html>
