apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: "{{ .Values.namespace }}"
spec:
  type: "{{ .Values.nginx.service.type }}"
  ports:
    - port: 80
      targetPort: 80
      nodePort: "{{ .Values.nginx.service.nodePort }}"
  selector:
    app: nginx
