apiVersion: v1
kind: ConfigMap
metadata:
  name: project-nginx-config
  namespace: {{ .Values.namespace }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Raz-Config-Web</title></head>
    <body>
      <h1>Hello from This Is My Page!</h1>
      <p>This page is served from a ConfigMap.</p>
    </body>
    </html>
