apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: project-complex-app-metrics
  namespace: {{ .Values.namespace }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ include "project3.name" . }}
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}