
name: Project K3s Monitoring CI/CD Pipeline

on: [push]

jobs:
  build-deploy-monitoring:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install K3s (if not already installed)
        run: |
          if ! command -v k3s &> /dev/null; then
            curl -sfL https://get.k3s.io | sudo sh -
          else
            echo "K3s already installed"
          fi

      - name: Export kubeconfig
        run: |
          echo "KUBECONFIG=/etc/rancher/k3s/k3s.yaml" >> $GITHUB_ENV

      - name: Install Helm (if needed)
        run: |
          if ! command -v helm &> /dev/null; then
            curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          fi

      - name: Run monitoring install.sh script
        run: |
          chmod +x install.sh
          ./project-dev-3/install.sh

      - name: Wait for monitoring pods to be ready
        run: |
          kubectl wait --for=condition=Ready pods --all -n project-monitoring --timeout=180s
          kubectl get pods -n project-monitoring

      - name: Test access to Grafana or Prometheus NodePort (optional)
        run: |
          echo "Testing access to NodePort (example on port 30090)..."
          curl -s http://localhost:30090 || echo "Port not accessible"

      - name: Run monitoring uninstall.sh script
        run: |
          chmod +x uninstall.sh
          ./project-dev-3/uninstall.sh
