name: Project K3s Monitoring CI/CD Pipeline

on: [push]

jobs:
  build-deploy-monitoring:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install K3s (if not already installed)
        run: |
          if ! command -v k3s &> /dev/null; then
            curl -sfL https://get.k3s.io | sudo sh -
          else
            echo "K3s already installed"
          fi

      - name: Set up kubeconfig for current user
        run: |
          mkdir -p ~/.kube
          sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
          sudo chown $USER ~/.kube/config
          echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

      - name: Install Helm (if not already installed)
        run: |
          if ! command -v helm &> /dev/null; then
            curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          else
            echo "Helm already installed"
          fi

      - name: Make scripts executable
        run: |
          chmod +x install-project-dev-3.sh uninstall-project-dev-3.sh get-grafana-dash.sh
          echo "Scripts are now executable."

      - name: Run install-project-dev-3.sh
        run: ./install-project-dev-3.sh

      - name: Wait for monitoring pods to be ready
        run: |
          kubectl wait --for=condition=Ready pods --all -n project-monitoring --timeout=180s
          kubectl get pods -n project-monitoring

      - name: Port-forward Grafana and run get-grafana-dash.sh
        run: |
          # Run port-forward in background
          kubectl port-forward -n project-monitoring svc/grafana 30900:80 &
          PORT_FORWARD_PID=$!

          # Wait briefly to ensure port-forward is active
          sleep 10

          # Run script to fetch dashboards
          ./get-grafana-dash.sh

          # Clean up port-forward
          kill $PORT_FORWARD_PID

      - name: Run uninstall-project-dev-3.sh
        run: ./uninstall-project-dev-3.sh
