name: Project K3s Monitoring CI/CD Pipeline

on: [push]

jobs:
  build-deploy-monitoring:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install K3s (if not already installed)
        run: |
          if ! command -v k3s &> /dev/null; then
            curl -sfL https://get.k3s.io | sudo sh -
          else
            echo "K3s already installed"
          fi

      - name: Export kubeconfig
        run: |
          echo "KUBECONFIG=/etc/rancher/k3s/k3s.yaml" >> $GITHUB_ENV

      - name: Install Helm (if needed)
        run: |
          if ! command -v helm &> /dev/null; then
            curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          fi

      - name: Make install/uninstall scripts executable
        run: |
          chmod +x install-project-dev-3.sh uninstall-project-dev-3.sh

      - name: Run install-project-dev-3.sh
        run: ./install-project-dev-3.sh

      - name: Wait for monitoring pods to be ready
        run: |
          kubectl wait --for=condition=Ready pods --all -n project-monitoring --timeout=180s
          kubectl get pods -n project-monitoring

      - name: Run uninstall-project-dev-3.sh
        run: ./uninstall-project-dev-3.sh

